#!/usr/bin/env python3


def checkout_func():
    from csProjectManager.projectManager import (
        csGetRepository,
        csRunCommand,
        csGetPrecompiledLib,
    )

    repo_cs_url = "git@github.com"
    repo_https_url = "https://api.github.com/repos/"
    branch = "cs-main"

    _ = repo_https_url
    _ = csRunCommand
    _ = csGetPrecompiledLib

    csGetRepository(
        repo_cs_url,
        "cscosine/csCMake.git",
        "csCMake",
        branch,
        needCMakeUserPathFile=False,
    )

    _ = csGetRepository
    _ = csRunCommand
    _ = csGetPrecompiledLib
    pass


def build_func():
    from csProjectManager.projectManager import csWorkflow

    # for interface only libraries, generate a single configuration only (use release)
    # note, use the {} to enable properly the -po option (preset only)
    presetRelease = {
        "linux": ["linux-ninja{release}", "linux-ninja-multi-config-clang"],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    # use {debug|release}
    presetDebugRelease = {
        "linux": ["linux-ninja{debug|release}", "linux-ninja-multi-config-clang"],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    # use {debug|release|relWithDebInfo|paranoid}
    presetsAll = {
        "linux": [
            "linux-ninja{debug|release|relWithDebInfo|paranoid}",
            "linux-ninja-multi-config-clang",
        ],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    _ = presetRelease
    _ = presetDebugRelease
    _ = presetsAll

    _ = csWorkflow


############################################################################################
## -- BEGIN AUTOGENERATED CODE - DO NOT EDIT BELOW THIS POINT - IT WILL BE OVERWRITTEN -- ##


def main():
    import os
    import sys

    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    # Ensure script runs from its own directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    current_dir = os.getcwd()

    if current_dir != script_dir:
        print(
            f"Warning: The current directory ({current_dir}) is not the same as the script's directory ({script_dir}), changing to {script_dir}"
        )
        os.chdir(script_dir)

    # get the repository to setup the project,
    csProjectManager_dir = "csProjectManager"
    csProjectManager_base_url = "git@github.com"
    csProjectManager_repo = "cscosine/csProjectManager.git"
    csProjectManager_branch = "cs-main"

    # if it does not exists, clone it
    if not os.path.isdir(csProjectManager_dir):
        try:
            print(
                f"Cloning the repository {csProjectManager_base_url}:{csProjectManager_repo} on branch {csProjectManager_branch} to {csProjectManager_dir}..."
            )
            Repo.clone_from(
                csProjectManager_base_url + ":" + csProjectManager_repo,
                csProjectManager_dir,
                branch=csProjectManager_branch,
            )
            print("... done")
        except GitCommandError as e:
            print(f"-- Git operation failed: {e}", file=sys.stderr)
            sys.exit(1)

    # Add csProjectManager directory to sys.path to allow module imports
    sys.path.insert(0, os.path.abspath(csProjectManager_dir))
    try:
        print("Successfully imported csProjectManager module.")

        from csProjectManager.projectManager import csSetupProject, RepoCheckoutCommands
        from csProjectManager.lib.preCommitHooks import is_pre_commit_installed

        # check if precommit is available, will fail with error message in case
        is_pre_commit_installed()

        csSetupProject(
            csProjectManager=RepoCheckoutCommands(
                directory=csProjectManager_dir,
                base_url=csProjectManager_base_url,
                repo=csProjectManager_repo,
                branch=csProjectManager_branch,
                needCMakeUserPathFile=False,
                generateDependentRepoAction=True,
            ),
            checkout_func=checkout_func,
            build_func=build_func,
            original_exec_dir=current_dir,
        )
    except ImportError as e:
        print(f"Failed to import csProjectManager: {e}", file=sys.stderr)
        sys.exit(1)


# Check if GitPython is installed
try:
    from git import Repo, GitCommandError
except ImportError:
    import sys

    print(
        "GitPython is not installed. Please install it using, for example, pip install GitPython",
        file=sys.stderr,
    )
    sys.exit(1)

if __name__ == "__main__":
    main()

## --  END AUTOGENERATED CODE - DO NOT EDIT ABOVE THIS POINT - IT WILL BE OVERWRITTEN --  ##
############################################################################################
