#!/usr/bin/env python3


def checkout_func():
    from csProjectManager.projectManager import (
        csGetRepository,
        csRunCommand,
        csGetPrecompiledLib,
    )

    repo_cs_url = "git@github.com"
    repo_https_url = "https://api.github.com/repos/"

    _ = repo_https_url
    _ = csGetPrecompiledLib

    csRunCommand(
        name="Install prerequisites for Linux",
        command="./installRequirements-linux.sh",
        os_name="linux",
    )

    csGetRepository(
        base_url=repo_cs_url,
        repo="qt/qt5.git",
        repo_dir="qt6",
        tag="v6.10.2",
        needCMakeUserPathFile=False,
        generateDependentRepoAction=False,
        useActionsOrgAccessToken=False,
    )

    # take a look to https://wiki.qt.io/Building_Qt_6_from_Git

    csRunCommand(
        name="Init Qt Submodules (linux)",
        command="./init-repository-linux.sh",
        os_name="linux",
    )
    csRunCommand(
        name="Init Qt Submodules (windows)",
        command="cmd /c init-repository-windows.bat",
        os_name="windows",
    )

    _ = csGetPrecompiledLib


def build_func():
    from csProjectManager.projectManager import csWorkflow, csCustomBuild

    # for interface only libraries, generate a single configuration only (use release)
    # note, use the {} to enable properly the -po option (preset only)
    cutstomCommandRelease = {
        # note: the commands are run in the repo directory
        "linux": [("linux-gcc", ["../build-repository-linux.sh"])],
        "windows": [
            ("windows-msvc2022-x64", ["cmd /c ..\\build-repository-windows.bat"])
        ],
    }

    csCustomBuild(repo_dir="qt6", os_presets_dict=cutstomCommandRelease)

    _ = csWorkflow


############################################################################################
## -- BEGIN AUTOGENERATED CODE - DO NOT EDIT BELOW THIS POINT - IT WILL BE OVERWRITTEN -- ##


def main():
    import os
    import sys

    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    # Ensure script runs from its own directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    current_dir = os.getcwd()

    if current_dir != script_dir:
        print(
            f"Warning: The current directory ({current_dir}) is not the same as the script's directory ({script_dir}), changing to {script_dir}"
        )
        os.chdir(script_dir)

    # get the repository to setup the project,
    csProjectManager_dir = "csProjectManager"
    csProjectManager_base_url = "git@github.com"
    csProjectManager_repo = "cscosine/csProjectManager.git"
    csProjectManager_branch = "cs-main"

    # if it does not exists, clone it
    if not os.path.isdir(csProjectManager_dir):
        try:
            print(
                f"Cloning the repository {csProjectManager_base_url}:{csProjectManager_repo} on branch {csProjectManager_branch} to {csProjectManager_dir}..."
            )
            Repo.clone_from(
                csProjectManager_base_url + ":" + csProjectManager_repo,
                csProjectManager_dir,
                branch=csProjectManager_branch,
            )
            print("... done")
        except GitCommandError as e:
            print(f"-- Git operation failed: {e}", file=sys.stderr)
            sys.exit(1)

    # Add csProjectManager directory to sys.path to allow module imports
    sys.path.insert(0, os.path.abspath(csProjectManager_dir))
    try:
        print("Successfully imported csProjectManager module.")

        from csProjectManager.projectManager import csSetupProject, RepoCheckoutCommands
        from csProjectManager.lib.preCommitHooks import is_pre_commit_installed

        # check if precommit is available, will fail with error message in case
        is_pre_commit_installed()

        csSetupProject(
            csProjectManager=RepoCheckoutCommands(
                directory=csProjectManager_dir,
                base_url=csProjectManager_base_url,
                repo=csProjectManager_repo,
                branch=csProjectManager_branch,
                needCMakeUserPathFile=False,
                generateDependentRepoAction=True,
            ),
            checkout_func=checkout_func,
            build_func=build_func,
            original_exec_dir=current_dir,
        )
    except ImportError as e:
        print(f"Failed to import csProjectManager: {e}", file=sys.stderr)
        sys.exit(1)


# Check if GitPython is installed
try:
    from git import Repo, GitCommandError
except ImportError:
    import sys

    print(
        "GitPython is not installed. Please install it using, for example, pip install GitPython",
        file=sys.stderr,
    )
    sys.exit(1)

if __name__ == "__main__":
    main()

## --  END AUTOGENERATED CODE - DO NOT EDIT ABOVE THIS POINT - IT WILL BE OVERWRITTEN --  ##
############################################################################################
